# Generated by Django 5.2 on 2026-06-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out_time',
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.TimeField()),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hrms.attendance')),
            ],
            options={
                'ordering': ['clock_in_time'],
            },
        ),
    ]
