# Generated by Django 5.2 on 2026-06-26 13:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_leave_reason_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_bonus_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='% of contract_value awarded to the bid writer', max_digits=5)),
                ('presales_bonus_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='% of contract_value awarded to the presales person', max_digits=5)),
                ('flat_bonus_per_bid', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Flat bonus per submitted bid when contract_value is absent', max_digits=10)),
            ],
            options={
                'verbose_name': 'Bonus Configuration',
                'verbose_name_plural': 'Bonus Configuration',
            },
        ),
    ]
