# Generated by Django 6.0.6 on 2026-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_bonusconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='months_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advancesalaryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recovered', 'Recovered')], default='pending', max_length=20),
        ),
    ]
