# Generated by Django 6.0.6 on 2026-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_seed_months_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='monthly_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
