# Generated by Django 5.2 on 2026-06-29 19:40

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_attachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.attachment_path),
        ),
    ]
