# Generated by Django 5.2 on 2026-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_backlogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('requirement', 'Requirement'), ('issue', 'Issue'), ('bid', 'Bid')], default='task', max_length=15),
        ),
    ]
