# Generated by Django 5.2 on 2026-06-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('solicitation_number', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('due_date', models.DateTimeField()),
                ('bid_link', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source_date', models.DateTimeField(auto_now_add=True)),
                ('pre_bid_info', models.TextField(blank=True)),
                ('qa_notes', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('no_go', 'No Go'), ('unsubmitted', 'Unsubmitted'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='in_progress', max_length=20)),
                ('portal_username', models.CharField(blank=True, max_length=255)),
                ('portal_password', models.CharField(blank=True, max_length=255)),
                ('internal_deadline', models.DateTimeField(blank=True, null=True)),
                ('submission_method', models.CharField(blank=True, choices=[('portal', 'Portal'), ('physical', 'Physical'), ('email', 'Email'), ('portal_and_physical', 'Portal and Physical'), ('fax', 'Fax'), ('email_and_physical', 'Email and Physical')], max_length=30)),
                ('date_of_review', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.client')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bids', to='bids.bidopportunity')),
            ],
        ),
    ]
