# Generated by Django 5.2 on 2026-06-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('portal_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_credentials', to='bids.client')),
            ],
            options={
                'ordering': ['state', 'portal_name'],
            },
        ),
    ]
