# Generated by Django 5.2 on 2026-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_portalcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalcredential',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portalcredential',
            name='portal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
