# Generated by Django 5.2 on 2026-06-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_portal_credential_field_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalcredential',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
