# Generated by Django 5.2 on 2026-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_client_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbid',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated or awarded contract value (USD)', max_digits=14, null=True),
        ),
    ]
