# Generated by Django 5.2 on 2026-06-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_bid_assignment_remove_writer_presales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
