# Generated by Django 5.2 on 2026-06-30 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_alter_bidassignment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidopportunity',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidopportunity',
            name='poc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bidopportunity',
            name='prewriter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prewritten_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BidOpportunityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='bid_oc_files/')),
                ('link', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_attachments', to='bids.bidopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBidProposalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='bid_proposal_files/')),
                ('link', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_files', to='bids.clientbid')),
            ],
        ),
    ]
