# Generated by Django 5.2 on 2026-07-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0011_bid_opportunity_status_client_linked_user_portal_cred_restructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidopportunity',
            name='solicitation_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
