# Generated by Django 5.2 on 2026-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_submitted', 'Leave submitted'), ('incentive_granted', 'Incentive granted'), ('incentive_sent', 'Incentive sent'), ('task_assigned', 'Task assigned')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
