# Generated by Django 6.0.6 on 2026-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_submitted', 'Leave submitted'), ('incentive_granted', 'Incentive granted'), ('incentive_sent', 'Incentive sent'), ('task_assigned', 'Task assigned'), ('document_received', 'Document received'), ('document_request', 'Document requested'), ('document_request_fulfilled', 'Document request fulfilled'), ('document_request_declined', 'Document request declined'), ('payslip_generated', 'Payslip generated'), ('advance_approved', 'Advance approved'), ('advance_rejected', 'Advance rejected')], max_length=40),
        ),
    ]
