# Generated by Django 5.2 on 2026-06-29 19:40

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentrequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.shared_document_path),
        ),
    ]
