# Generated by Django 5.2 on 2026-06-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='present_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_position',
            field=models.CharField(blank=True, choices=[('Proposal Writer', 'Proposal Writer'), ('Senior VP', 'Senior VP'), ('Team Lead', 'Team Lead'), ('Associate', 'Associate'), ('Administrative Assistant', 'Administrative Assistant'), ('Program Coordinator', 'Program Coordinator'), ('Data Collection Staff', 'Data Collection Staff')], max_length=50, null=True),
        ),
    ]
