# Generated by Django 5.2 on 2026-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_system', models.CharField(blank=True, help_text="e.g., 'System', 'Celery', 'Webhook'", max_length=50, null=True)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(blank=True, help_text='e.g. created, transition, deleted', max_length=50)),
                ('old_state', models.CharField(blank=True, max_length=50, null=True)),
                ('new_state', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('permission_keys', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded roles cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
