# Generated by Django 5.2 on 2026-07-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Client', 'Client')], max_length=20, unique=True)),
                ('permission_keys', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Type Permissions',
                'verbose_name_plural': 'User Type Permissions',
                'ordering': ['user_type'],
            },
        ),
    ]
